# Generated by Django 6.0.6 on 2026-07-15 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Fecha en la que comenzó el período menstrual.', verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, help_text='Se establece automáticamente cuando inicia el siguiente período.', null=True, verbose_name='Fecha de finalización')),
                ('expected_length', models.PositiveSmallIntegerField(default=28, help_text='Se utiliza para estimar la duración del ciclo hasta conocer su duración real.', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(45)], verbose_name='Duración esperada')),
                ('actual_length', models.PositiveSmallIntegerField(blank=True, help_text='Se calcula automáticamente al finalizar el ciclo.', null=True, verbose_name='Duración real')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CyclePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de finalización')),
            ],
            options={
                'verbose_name': 'Fase del ciclo',
                'verbose_name_plural': 'Fases del ciclo',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(verbose_name='Fecha del registro')),
                ('energy_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Muy baja'), (2, 'Baja'), (3, 'Normal'), (4, 'Alta'), (5, 'Muy alta')], null=True, verbose_name='Nivel de energía')),
                ('mood', models.CharField(blank=True, choices=[('happy', '😊 Feliz'), ('calm', '😌 Tranquila'), ('neutral', '😐 Neutral'), ('sad', '😔 Triste'), ('irritable', '😠 Irritable'), ('anxious', '😰 Ansiosa')], max_length=20, null=True, verbose_name='Estado de ánimo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Registro diario',
                'verbose_name_plural': 'Registros diarios',
                'ordering': ['log_date'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Información educativa que puede mostrarse a la usuaria.', verbose_name='Descripción')),
                ('estimated_percentage', models.DecimalField(decimal_places=2, help_text='Porcentaje aproximado que representa esta fase dentro del ciclo menstrual.', max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje estimado')),
                ('sort_order', models.PositiveSmallIntegerField(help_text='Orden en el que aparece la fase durante el ciclo.', unique=True, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('sort_order', models.PositiveSmallIntegerField(verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Síntoma',
                'verbose_name_plural': 'Síntomas',
                'ordering': ['category__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SymptomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('icon', models.CharField(blank=True, help_text='Emoji representativo de la categoría.', max_length=10, verbose_name='Ícono')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('sort_order', models.PositiveSmallIntegerField(unique=True, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría de síntoma',
                'verbose_name_plural': 'Categorías de síntomas',
                'ordering': ['sort_order'],
            },
        ),
    ]
