# Generated by Django 6.0.6 on 2026-07-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id_ciclo', models.AutoField(db_column='id_ciclo', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('duracion_esperada', models.IntegerField(default=28)),
                ('notas', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'ciclo',
            },
        ),
        migrations.CreateModel(
            name='CicloFase',
            fields=[
                ('id_ciclo_fase', models.AutoField(db_column='id_ciclo_fase', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'ciclo_fase',
            },
        ),
        migrations.CreateModel(
            name='EstadoAnimo',
            fields=[
                ('id_estado_animo', models.AutoField(db_column='id_estado_animo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'estado_animo',
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id_fase', models.AutoField(db_column='id_fase', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fase',
            },
        ),
        migrations.CreateModel(
            name='NivelEnergia',
            fields=[
                ('id_energia', models.AutoField(db_column='id_energia', primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('valor', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'nivel_energia',
            },
        ),
        migrations.CreateModel(
            name='RegistroCiclo',
            fields=[
                ('id_registro', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('sintomas', models.JSONField(default=list)),
                ('notas', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'registro_ciclo',
            },
        ),
    ]
