# Generated by Django 6.0.6 on 2026-07-09 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='persona',
            field=models.ForeignKey(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ciclofase',
            name='ciclo',
            field=models.ForeignKey(db_column='ciclo_id', on_delete=django.db.models.deletion.CASCADE, to='cycles.ciclo'),
        ),
        migrations.AddField(
            model_name='ciclofase',
            name='fase',
            field=models.ForeignKey(db_column='fase_id', on_delete=django.db.models.deletion.CASCADE, to='cycles.fase'),
        ),
        migrations.AddField(
            model_name='registrociclo',
            name='animo',
            field=models.ForeignKey(db_column='animo_id', on_delete=django.db.models.deletion.CASCADE, to='cycles.estadoanimo'),
        ),
        migrations.AddField(
            model_name='registrociclo',
            name='ciclo',
            field=models.ForeignKey(db_column='ciclo_id', on_delete=django.db.models.deletion.CASCADE, to='cycles.ciclo'),
        ),
        migrations.AddField(
            model_name='registrociclo',
            name='energia',
            field=models.ForeignKey(db_column='energia_id', on_delete=django.db.models.deletion.CASCADE, to='cycles.nivelenergia'),
        ),
        migrations.AddIndex(
            model_name='ciclo',
            index=models.Index(fields=['persona', '-fecha_inicio'], name='ciclo_persona_226474_idx'),
        ),
        migrations.AddIndex(
            model_name='ciclofase',
            index=models.Index(fields=['ciclo', 'fecha_inicio', 'fecha_fin'], name='ciclo_fase_ciclo_i_bc646a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='registrociclo',
            unique_together={('ciclo', 'fecha')},
        ),
    ]
