# Generated by Django 6.0.6 on 2026-07-15 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to=settings.AUTH_USER_MODEL, verbose_name='Usuaria'),
        ),
        migrations.AddField(
            model_name='cyclephase',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='cycles.cycle', verbose_name='Ciclo'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='cycles.cycle', verbose_name='Ciclo'),
        ),
        migrations.AddField(
            model_name='cyclephase',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycles.phase', verbose_name='Fase'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='symptoms',
            field=models.ManyToManyField(blank=True, related_name='daily_logs', to='cycles.symptom', verbose_name='Síntomas'),
        ),
        migrations.AddField(
            model_name='symptom',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='symptoms', to='cycles.symptomcategory', verbose_name='Categoría'),
        ),
        migrations.AddIndex(
            model_name='cycle',
            index=models.Index(fields=['user', '-start_date'], name='cycles_cycl_user_id_102438_idx'),
        ),
        migrations.AddConstraint(
            model_name='cycle',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='cycle_end_date_after_start_date'),
        ),
        migrations.AddIndex(
            model_name='cyclephase',
            index=models.Index(fields=['cycle', 'start_date', 'end_date'], name='cycle_phase_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='cyclephase',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='cycle_phase_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='cyclephase',
            constraint=models.UniqueConstraint(fields=('cycle', 'phase'), name='unique_phase_per_cycle'),
        ),
        migrations.AddIndex(
            model_name='dailylog',
            index=models.Index(fields=['cycle', 'log_date'], name='daily_log_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailylog',
            constraint=models.UniqueConstraint(fields=('cycle', 'log_date'), name='unique_daily_log_per_day'),
        ),
        migrations.AddConstraint(
            model_name='symptom',
            constraint=models.UniqueConstraint(fields=('category', 'sort_order'), name='unique_symptom_order_per_category'),
        ),
    ]
