# Generated by Django 6.0.6 on 2026-07-12 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cyclephase',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='cycles.cycle'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cycles.cycle'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='energy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycles.energylevel'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycles.mood'),
        ),
        migrations.AddField(
            model_name='cyclephase',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycles.phase'),
        ),
        migrations.AddIndex(
            model_name='cycle',
            index=models.Index(fields=['user', '-start_date'], name='cycle_user_id_d5bacb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('cycle', 'date')},
        ),
        migrations.AddIndex(
            model_name='cyclephase',
            index=models.Index(fields=['cycle', 'start_date', 'end_date'], name='cycle_phase_cycle_i_cfafa6_idx'),
        ),
    ]
