# Generated by Django 6.0.6 on 2026-07-15 01:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('category_type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Gasto')], max_length=10, verbose_name='Tipo')),
                ('icon', models.CharField(blank=True, help_text='Emoji representativo de la categoría.', max_length=20, verbose_name='Ícono')),
                ('is_default', models.BooleanField(default=True, help_text='Indica si la categoría fue creada por el sistema.', verbose_name='Categoría del sistema')),
                ('is_active', models.BooleanField(default=True, help_text='Permite ocultar la categoría sin eliminarla.', verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor de la transacción.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('transaction_date', models.DateField(verbose_name='Fecha de la transacción')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional de la transacción.', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
