# Generated by Django 6.0.6 on 2026-07-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la transacción se encuentra activa.', verbose_name='Activa'),
        ),
    ]
