# Generated by Django 6.0.6 on 2026-07-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('source', models.CharField(max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'insight',
            },
        ),
    ]
