# Generated by Django 6.0.6 on 2026-07-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id_insight', models.AutoField(db_column='id_insight', primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fuente', models.CharField(max_length=10)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('total_transacciones', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'insight',
            },
        ),
    ]
