# Generated by Django 6.0.6 on 2026-07-15 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('finance', 'Finanzas'), ('symptom', 'Síntomas'), ('mood', 'Estado de ánimo'), ('energy', 'Energía'), ('general', 'General')], help_text='Clasificación del insight.', max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(help_text='Título corto que resume el insight.', max_length=100, verbose_name='Título')),
                ('message', models.TextField(help_text='Contenido del insight mostrado a la usuaria.', verbose_name='Mensaje')),
                ('shown_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de visualización')),
                ('cycle', models.ForeignKey(help_text='Ciclo menstrual utilizado para generar el insight.', on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='cycles.cycle', verbose_name='Ciclo')),
                ('phase', models.ForeignKey(help_text='Fase del ciclo sobre la que trata el insight.', on_delete=django.db.models.deletion.PROTECT, related_name='insights', to='cycles.phase', verbose_name='Fase')),
            ],
            options={
                'verbose_name': 'Insight',
                'verbose_name_plural': 'Insights',
                'ordering': ['-shown_at'],
            },
        ),
    ]
