# Generated by Django 6.0.6 on 2026-07-15 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL, verbose_name='Usuaria'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['user', '-shown_at'], name='insight_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['user', 'type'], name='insight_user_type_idx'),
        ),
    ]
