# Generated by Django 5.1.3 on 2026-07-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='type',
            field=models.CharField(choices=[('cycle', 'Ciclo'), ('daily_log', 'Registro diario'), ('finance', 'Finanzas'), ('mixed', 'Mixto'), ('symptom', 'Síntomas'), ('mood', 'Estado de ánimo'), ('energy', 'Energía'), ('general', 'General')], help_text='Clasificación del insight.', max_length=20, verbose_name='Tipo'),
        ),
    ]
